name: "Model"
description: "My first real add-on!"
version: "1.0.1"
slug: "model"
init: false
arch:
  - aarch64
  - i386
options:
  token: aeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIyYmYxMjUzMWJlMDM0ODdlYjA5MzU3MjRhMDAxYzBiOCIsImlhdCI6MTY5NjkxMzMzNCwiZXhwIjoyMDEyMjczMzM0fQ.EmJ1qh1RyjrtSr9cE1o8psdmVCQuT_dUkl4K-A5GIzI
  entities:
    - binary_sensor.dinning_room_sensor_presence
    - binary_sensor.hallway_motion_and_intensity_sensor_occupancy
    - binary_sensor.jack_room_sensor_presence
schema:
  token: str
  entities:
    - str
